config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
  
    def about
    end
  
    def contact
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Boutique de Jouer</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Bootstrap CSS via CDN -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <%= link_to 'Boutique de Jouer', root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to 'Accueil', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'À propos', about_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Contact', contact_path, class: 'nav-link' %>
          </li>
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= form_tag(destroy_user_session_path, method: :delete, class: 'd-flex') do %>
                <%= submit_tag 'Déconnexion', class: 'btn btn-outline-danger me-2' %>
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Inscription', new_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Connexion', new_user_session_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container mt-5">
    <%= yield %>  <!-- C'est ici que le contenu des autres pages sera injecté -->
  </div>

  <!-- jQuery, Popper.js, and Bootstrap JavaScript via CDN -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
</body>
</html>

app/views/pages/about.html.erb
<div class="container mt-5">
  <div class="alert alert-info">
    <h2>Bienvenue dans notre boutique de jeux en ligne !</h2>
    <p>Nous sommes ravis de vous accueillir sur notre plateforme dédiée aux jeux vidéo. Chez Microarnak, nous vous proposons une sélection soigneusement choisie de jeux pour tous les types de joueurs.</p>
    <p>Découvrez notre collection diversifiée qui comprend des titres pour toutes les occasions : des jeux décontractés pour le quotidien aux jeux immersifs pour les passionnés.</p>
    <p>Notre équipe est passionnée par les jeux vidéo et s'engage à vous offrir une expérience d'achat exceptionnelle. Explorez nos différentes catégories, consultez nos recommandations et trouvez les jeux parfaits pour vous divertir et vous amuser.</p>
    <p>Nous mettons un point d'honneur à sélectionner des titres de qualité et à vous offrir un service clientèle irréprochable. Votre satisfaction est notre priorité absolue.</p>
    <p>Que vous soyez à la recherche des dernières nouveautés ou de classiques intemporels, nous avons ce qu'il vous faut. Parcourez notre boutique en ligne dès maintenant et laissez-vous inspirer par nos collections de jeux uniques.</p>
    <p>Merci de votre visite et à bientôt sur Microarnak !</p>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="container mt-5">
  <h1>Contactez-nous</h1>
  <%= form_with url: contact_path, method: :post, local: true do |form| %>
    <div class="form-group">
      <%= form.label :name, "Nom:" %>
      <%= form.text_field :name, class: "form-control", placeholder: "Votre nom" %>
    </div>
    <div class="form-group">
      <%= form.label :email, "Email:" %>
      <%= form.email_field :email, class: "form-control", placeholder: "Votre email" %>
    </div>
    <div class="form-group">
      <%= form.label :message, "Message:" %>
      <%= form.text_area :message, class: "form-control", placeholder: "Votre message" %>
    </div>
    <%= form.submit "Envoyer", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="container mt-5">
  <h1>Les jeux du moment</h1>
  <section class="py-3">
    <div class="container px-4 px-lg-5 mt-5">
      <div class="w row-cols-md-3 row-cols-xl-4 justify-content-center">
        <!-- Loop through games collection -->
        <% @games.each do |game| %>
          <div class="col mb-5">
            <div class="card h-100">
              <!-- Product image-->
              <img class="card-img-top" src="<%= game.image_url %>" alt="<%= game.name %>">
              <!-- Product details-->
              <div class="card-body p-1">
                <div class="d-flex txt-color">
                  <!-- Product name-->
                  <h5 class="fw-bolder"><%= game.name %></h5>
                  <!-- Product price-->
                  <%= game.price %>€
                </div>
              </div>
              <!-- Product actions-->
              <div class="card-footer p-1 pt-0 border-top-0 bg-transparent">
                <div class="d-flex txt-color">
                  <a class="btn btn-outline-dark mt-auto" href="<%= game.link %>">
                    <%= game.price == 0 ? 'Gratuit' : 'Acheter' %>
                  </a>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>
</div>